Add awesome stuffs
natelistrom/hello-world pull request #3
Opened 2016-04-26 20:22 UTC by natelistrom

2016-07-06 21:04 UTC, natelistrom commented
@natelistrom does this recognize @mentions?

2016-07-06 21:05 UTC, natelistrom commented
@natelistrom you need to fix #4

2016-08-19 17:12 UTC, natelistrom commented
Closing this as it is not helpful.

2016-09-02 13:01 UTC, natelistrom commented
# MOAAAARRR text!

2016-09-19 15:20 UTC, natelistrom commented on README.md
>  (by one character)
Whitespace

2016-09-19 15:21 UTC, natelistrom commented on README.md
> +Here's some more stuffs.
MOAR whitespace

2016-09-19 15:21 UTC, natelistrom reviewed
whitespace

2016-09-19 15:21 UTC, natelistrom reviewed
Comment

2016-09-19 15:22 UTC, natelistrom commented on README.md
>  (by one character)
This is just silly.

2016-09-19 15:23 UTC, natelistrom commented on README.md
> +Here's some more stuffs.
This is serious

2016-09-22 14:02 UTC, natelistrom commented on README.md
> +
Starting a review...

2016-09-22 14:02 UTC, natelistrom commented on README.md
> +Here's some more stuffs.
Adding a review comment...

2016-09-22 14:02 UTC, natelistrom commented on README.md
>  Extra stuff.
Adding a second review comment.

2016-09-22 14:02 UTC, natelistrom reviewed
You should add more foo to the bar.

2016-09-22 18:25 UTC, mmitrik commented on README.md
>  Extra stuff.
I agree with you

2016-09-22 18:25 UTC, mmitrik commented on README.md
>  (by one character)
+1 (start review)

2016-09-22 18:26 UTC, mmitrik commented on README.md
> +
ok

2016-09-22 18:26 UTC, mmitrik commented on README.md
> +Here's some more stuffs.
not important

2016-09-22 18:26 UTC, mmitrik commented on README.md
> +Here's some more stuffs.
I also notcied this thing Nate didn't comment on

2016-09-22 18:27 UTC, mmitrik requested changes
Here's my feedback.  take it or leave it

2016-09-22 18:29 UTC, mmitrik commented
put my feedback here

2016-12-08 21:25 UTC, closed without merging